### ISSUE TITLE
Payment REST API always return 403

### ISSUE THREAD

**Issue by shulhi** [paypal/paypal-checkout#701] opened 2018-05-30 02:41 UTC
### Description

Paypal version:
```
> paypal.version
"4.0.203"
```
It happens consistently. I've tried resetting/recreating my credentials but nothing helps.

### Steps to reproduce
```javascript

<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<div id="paypal-button-container"></div>

<script>

    // Render the PayPal button

    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // Specify the style of the button

        style: {
            label: 'checkout',
            size:  'small',    // small | medium | large | responsive
            shape: 'pill',     // pill | rect
            color: 'gold'      // gold | blue | silver | black
        },

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'AQN-PKzqzrP6qrAFVS37NSvbbtGX_Rx9Ob5VzSUA8uoZS7wWX-I8jzADnJKJnZ78r-XTRFVjbkIIObPQ',
            production: '<insert production client id>'
        },

        payment: function(data, actions) {
            return actions.payment.create({
                payment: {
                    transactions: [
                        {
                            amount: { total: '0.01', currency: 'USD' }
                        }
                    ]
                }
            });
        },

        onAuthorize: function(data, actions) {
            return actions.payment.execute().then(function() {
                window.alert('Payment Complete!');
            });
        }

    }, '#paypal-button-container');

</script>
```

request header, 
```
POST /v1/payments/payment HTTP/1.1
Host: www.sandbox.paypal.com
Connection: keep-alive
Content-Length: 225
Pragma: no-cache
Cache-Control: no-cache
accept: application/json
Origin: https://www.sandbox.paypal.com
authorization: Bearer A21AAEpot_Nqu4FG88UH7XlyWsUXF3838nB37SfCP4bNegFu2WiDoTjOqS1wcRnceGJqKgxQTnWPdNpZcbf4U99-JQuHHSrbA
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
content-type: application/json
DNT: 1
Referer: https://www.sandbox.paypal.com/webapps/hermes/button?env=sandbox&style.label=checkout&style.size=small&style.shape=pill&style.color=gold&sessionID=1b906be256_gazdumzrhiydc&buttonSessionID=ca8ea45ef3_gazdumzrhi2da&funding.disallowed=venmo&funding.remembered=paypal&locale.x=en_US&logLevel=warn&uid=7fb74d8a72&version=4&xcomponent=1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: <redacted-too-long>
```

in console,
```javascript
{
    "name": "PERMISSION_DENIED",
    "message": "No permission for the requested operation",
    "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
    "debug_id": "7a7d5ff22060"
}
```

and this is also true when I try on https://developer.paypal.com/demo/checkout/#/pattern/checkout

### Affected browsers

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

I only tried with these two browsers.

**Comment by abarco** [comment] 2018-05-30 02:52
Hi @shulhi, thank for your report. Could you clarify if you're seeing this in production? or is this only in Sandbox?

**Comment by shulhi** [comment] 2018-05-30 03:01
@abarco Sorry but I don't have access to production yet since I am still working on my application.

**Comment by abarco** [comment] 2018-05-30 03:06
No worries. I'm afraid I can't reproduce your problem from my end. Could you try to replace `<script src="https://www.paypalobjects.com/api/checkout.js"></script>` with `<script src="http://paypalobjects.com/api/checkout.4.0.202.js"></script>` and see if that works for you?

**Comment by shulhi** [comment] 2018-05-30 03:10
@abarco still doesn't work. Can you try the code I posted with the same client-id? I have a feeling that something is wrong with my client id. I've tried changing it multiple times but still no dice.

**Comment by abarco** [comment] 2018-05-30 03:29
Ok, I see the problem. It seems your sandbox account is not set up to receive payments. Here is the scope associated to your access token `https://uri.paypal.com/services/subscriptions https://api.paypal.com/v1/vault/credit-card openid https://api.paypal.com/v1/vault/credit-card/.*`. As you can see, you are not set up with `https://api.paypal.com/v1/payments/.*` permissions and this is why the payments API is failing for your sandbox account. I believe you might need a business account to have this functionality. You can get more information at https://developer.paypal.com/docs/integration/admin/manage-apps/

This is outside of the scope of this project so I'll be closing this issue. Hope it helps!

**Closed by abarco** 2018-05-30 03:29 UTC

**Comment by shulhi** [comment] 2018-05-30 03:37
@abarco how can I check if my access token has access to certain API?

**Comment by shulhi** [comment] 2018-05-30 07:11
@abarco sorry to bug you again but I've look all over the documentations and through developer portal but I can't seem to find a way to grant access (payment API) to my account. My account is business account.
