### ISSUE TITLE
Error on closing PayPal window

### ISSUE THREAD

**Issue by mtshare** [paypal/paypal-checkout#132] opened 2016-12-09 08:45 UTC
An error occurs after closing PayPal's payment window during initializing.

Here is the screenshot:
[http://pasteboard.co/7ENhaxhkY.jpg](url)

**Comment by bluepnume** [comment] 2016-12-09 08:55
So, just to be clear -- you're clicking the paypal button, but closing the window before it loads?

**Comment by marcocristalli** [comment] 2016-12-09 08:56
Exactly ;)

**Comment by bluepnume** [comment] 2016-12-09 08:57
OK. This error was designed for iframe use-cases, in case the element is removed -- I'll probably disable this for the popup though, since it would need to be closed by the user.

Thanks for the catch.

**Comment by bluepnume** [comment] 2016-12-13 17:43
Fixed and ready for deploy.

**Comment by bluepnume** [comment] 2017-01-17 20:48
Pushed.

**Closed by bluepnume** 2017-01-17 20:48 UTC
Labels: bug
