### ISSUE TITLE
4.0.103 Angular4 - post-robot error

### ISSUE THREAD

**Issue by MrBlaise** [paypal/paypal-checkout#428] opened 2017-08-03 08:34 UTC
### Description

Please provide a short description of the issue here, along with:

- [X] All console logs during the time of the issue, especially error messages

I am using braintree-web + paypal-checkout on my Angular 4 website.
The paypal-checkout v4.0.95 worked fine, after I upgraded to v4.0.103 I am getting the follwoing errors:

![screenshot 2017-08-03 10 17 26](https://user-images.githubusercontent.com/3867275/28912646-63d636c6-7835-11e7-863b-f6cd0c9b575c.png)

After this the paypal integration seems to work, I am able to add payment methods most of the time, however this error did not occur before.

### Steps to reproduce

Rendering the paypal button using paypal.Button.render.

### Affected browsers

- [X] Chrome
- [X] Safari
- [X] Firefox

**Comment by MrBlaise** [comment] 2017-08-03 08:50
I tested different versions and this error first appears in the version 4.0.100.
4.0.99 works fine.

**Comment by MrBlaise** [comment] 2017-08-03 08:58
I suspect this commit might be the cause: 8de8b834d4e652e553667403a225e36aa3faabee

**Comment by bluepnume** [comment] 2017-08-03 09:05
Thanks for the report. I think I know the root cause. I'll try to get a fix for this out tomorrow.

**Comment by MrBlaise** [comment] 2017-08-03 09:19
Thanks a lot!

**Comment by bluepnume** [comment] 2017-08-09 20:43
The fix is pushed and your issue should now be resolved -- please let me know if you still see the problem. Thanks!

**Closed by bluepnume** 2017-08-09 20:43 UTC
Labels: bug, p2

**Comment by MrBlaise** [comment] 2017-08-31 09:56
This issue reappeared from the version 4.0.117 again @bluepnume

**Comment by AlanMenhennet** [comment] 2017-09-01 05:45
I'm also having this error, changing back to 4.0.113 resolved the issue for me

![image](https://user-images.githubusercontent.com/7446065/29956740-87acb332-8f2c-11e7-810a-c4e9f0201b0e.png)

**Comment by MrBlaise** [comment] 2017-09-01 05:48
@AlanMenhennet  4.0.116 works fine for me, it broke from the version 4.0.117
