### ISSUE TITLE
MS Edge version 38.14393.2068.0 is causing issues with the incontext checkout.

### ISSUE THREAD

**Issue by ppkarthik** [paypal/paypal-checkout#878] opened 2018-10-03 00:30 UTC
### Description

Buyer is able to login to the PayPal account and select funding source.
Upon clicking on Agree & Continue instead of the window closing the buyer is shown their account summary.

### Steps to reproduce

Merchant -- https://www.fun.com/ has this issue. We were able to reproduce the issue during checkout through the Edge browser.

Merchant example video -- https://drive.google.com/file/d/1_SEGMCqY4CPWucyuP_AYvzxmTADElRMU/view

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment] 2018-10-08 18:04
@vishakha94 can you give this a try when you have a spare sec and see if you can repro in Edge 38?

**Comment by ppkarthik** [comment] 2018-10-11 15:35
Hey guys any updates regarding this? Merchant is still waiting for an update from us.

**Comment by ppkarthik** [comment] 2018-10-16 15:37
@vishakha94 yes, i have seen this issue on two separate windows systems, even till yesterday morning. As far as i can see it this can be reproduced in any Edge browser. The issue occurs after the buyer clicks on continue in the paypal login

**Comment by vishakha94** [comment] 2018-10-16 16:10
Can you pls post the edge versions for both the systems you tried it on? @ppkarthik

**Comment by ppkarthik** [comment] 2018-10-16 16:15
@vishakha94 One system was 38.14393.2068.0, the other i assume will be the same since it was one of my team-mates with the same corporate settings.

**Comment by vishakha94** [comment] 2018-10-16 18:56
@ppkarthik Have you tried to update edge and see if the issue still persists? We are talking above versions 41 and above.

**Comment by ppkarthik** [comment] 2018-10-17 00:10
@vishakha94 no i dont have windows to update the edge version plus, we cannot ask all the customers on edge to upgrade to a later version right ?

**Comment by vishakha94** [comment] 2018-10-17 13:42
@ppkarthik I agree but Edge v38.x gets really low traffic and we need to know if this problem is actually reproducible in the more recent versions of Edge i.e v41 or v16 onwards.
See this for the correct versioning, Edge seems to be following two of these. https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history
We would need to know if these issues persist on the more recent versions.

**Comment by vuvutestaccount** [comment] 2018-11-19 19:42
Hello, 

I have a merchant using Microsoft Edge version 41.16299.726.0 (Microsoft Edge HTML 16.16299)
and has come across a similar issue. After signing into PayPal, the incontext window doesn't close and instead, redirects the customer back to the merchant's checkout page in the incontext window. This can be tested by adding the following item to the cart and signing into the website using the below credentials:

https://online3-qa.kitco.com/buy/3104INC/1-oz-Silver-Maple-Leaf-Incuse-Coin-9999-3104INC

Username: vupaypal@gmail.com
Password: vu12345

The issue does not occur in Chrome, Firefox, nor Safari as I have tested this on my end. Furthermore, I was able to duplicate the problem using the same Edge version and have screenshots from my test that I can forward for reference. 

Lastly, I know this isn't high on the priority list; however, the merchant plans to go live before Thanksgiving and is asking if we can expedite this.

**Comment by mcntsh** [comment] 2018-12-03 22:50
Hey @vuvutestaccount  and @ppkarthik there are quite a few reports mentioning a similar bug. Could you please see [this comment on issue #959](https://github.com/paypal/paypal-checkout/issues/959#issuecomment-443851819) and let me know if this solves your problem?

This will help us keep track of which ticket is related to which bug, since the example.com redirect can happen for a few different reasons.

**Comment by bluepnume** [comment] 2018-12-10 06:57
Closing this issue. We've made several fixes for IE/Edge in intranet and trusted mode. @mcntsh will be updating the docs with our latest recommendations.

**Closed by bluepnume** 2018-12-10 06:57 UTC
