### ISSUE TITLE
Succeeded authorization triggers onCancel event

### ISSUE THREAD

**Issue by neshke89** [paypal/paypal-checkout#137] opened 2016-12-13 11:28 UTC
Here's workflow:
I'm using servers side to generate agreement billing token.
After authorization cancel event is trigered but token is authorized succesfully.

-I've tested token using postman and PayPal api call for execution transaction with token returned in onCancel which was done sucessfully.

**Comment by bluepnume** [comment] 2016-12-13 17:35
Can you share your code? You're saying you're seeing both `onAuthorize` **and** `onCancel` called for the same transaction?

**Comment by bluepnume** [comment] 2016-12-14 00:24
OK we've managed to repro this. @abarco is working on a fix.

Thanks,
Daniel

**Comment by neshke89** [comment] 2016-12-14 02:15
It was a bussy day, sorry for not answering immediatelly.
As you've managed to repro, I'll just confirm behaviour.
It's triggering onCancel, not onAuthorize  even when paymen token was authorized.

**Comment by abarco** [comment] 2016-12-16 00:44
Hi @neshke89, we have a fix. You can expect it to be pushed by early Jan

**Comment by WayneUong** [comment] 2016-12-17 02:59
Hi @abarco, this issue is still not fixed in 4.0.37? This is breaking our subscriptions and we need it asap. Is there a temporary fix for now?

**Comment by abarco** [comment] 2016-12-19 18:35
Hi @WayneUong, I'm afraid there is no temporary fix for this. The issue is not part of the checkout script, but the paypal app. We won't be able to push until early Jan.

**Comment by bluepnume** [comment] 2017-01-12 19:43
@abarco can you confirm this works after yesterday's checkout push?

**Comment by abarco** [comment] 2017-01-12 20:12
Yup, closing the issue. The correct handler is being called.

**Closed by abarco** 2017-01-12 20:12 UTC
Labels: bug, p1
