### ISSUE TITLE
Re: Can not go to checkout on mobile Safari (iOS 11.3)

### ISSUE THREAD

**Issue by MacFiss** [paypal/paypal-checkout#733] opened 2018-07-05 05:47 UTC
### Description

We've had customers on our platform report a similar issue with PayPal buttons not working on iOS. After a day of debugging, we were able to reliably reproduce the issue on iOS 11.3 and 11.3.1.

paypal.version in these tests is 4.0.202

### Steps to reproduce

Note, this example page has an empty touchstart event handler defined.

- Visit http://scotty.is/tests/paypal3/index.html on iOS 11.3 or 11.4
- Swipe to scroll to the bottom of the page so the button is off screen, then swipe back up so the button is on screen again.
- Fast tap the button, only a hover is triggered on the modal, PayPal checkout is not triggered.
- Long tap the button and PayPal checkout will be triggered.

Here’s a video that shows this in action: https://www.dropbox.com/s/0mbvgmv84lj5nq5/paypal-fasttap-issue.mov?dl=0

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

[@snelson, described the problem](https://github.com/paypal/paypal-checkout/issues/657#issuecomment-387810331)

**Comment by bluepnume** [comment] 2018-07-09 20:55
Thanks for the report! Looks like a duplicate of https://github.com/paypal/paypal-checkout/issues/657 though -- can we keep the discussion there? @khanghoang is currently working on this one.

**Closed by bluepnume** 2018-07-09 20:55 UTC
