### ISSUE TITLE
Express checkout payment not working in iPhones

### ISSUE THREAD

**Issue by etakh** [paypal/paypal-checkout#591] opened 2018-02-07 08:15 UTC
I am using Express checkout js SDK client-side REST integration in my hybrid application and Express checkout functionality is not working properly in iPhones.  I am using the same code in the below documentation: https://developer.paypal.com/demo/checkout/#/pattern/client  
The issues facing in iPhones while doing payment with credit/debit cards are:
1. Payment popup is not responsive in iPhones, especially in iPhone5 the popup is not completely visible to the user.
2. Payment popup close button is not visible in iPhone 5. The button is visible in iPhone6 but sometimes the close function is not properly working.
3. Not able to do payment. While clicking 'continue' button after entering all details(card information and billing info), the user again redirected to the top of the page. 
4. Not able to close the payment popup by clicking outside the popup. 
5.  Payment popup scroll is not properly working. Sometimes the scroll working with a delay. Always the page will be scrolled to the top of the page if the user tries to navigate back or proceed payment.

The screenshots of payment popup are given below.
![img_0177](https://user-images.githubusercontent.com/32954111/35905426-1edf4078-0c0d-11e8-9c4f-eeaf33c6082d.PNG)
![img_0178](https://user-images.githubusercontent.com/32954111/35905428-1f149066-0c0d-11e8-8688-2a13448f4c40.PNG)

**Comment by bluepnume** [comment] 2018-04-19 00:44
@khanghoang - can you take a look?

**Comment by khanghoang** [comment] 2018-04-19 19:51
@bluepnume sure, I will

**Comment by khanghoang** [comment] 2018-04-23 23:03
@etakh sorry I couldn't reproduce this bug. Would you mind to give us more information?
```
- Is it on the real device or simulator?
- What is your iOS version?
- WebView type: UIWebView | WKWebView | SafariViewController
- What is kind of hybrid application? Cordova?
```

**Comment by akhilaet** [comment] 2018-04-24 05:58
@khanghoang Please find the details below.

- Real device
- Version 11.2.6
- Webview type: UIWebView
- Hybrid application: Ionic v1

**Comment by kdenz** [comment] 2018-04-24 09:06
Same problem here!
I'm using UIWebView for our React Native app
Tested on iOS 10 and 11

**Comment by etakh** [comment] 2018-04-24 09:10
@khanghoang I hace 

Real device
Version 11.2.6
Webview type: UIWebView
Hybrid application: Ionic v1

**Comment by etakh** [comment] 2018-04-24 09:10
@khanghoang Please find the details below.

Real device
Version 11.2.6
Webview type: UIWebView
Hybrid application: Ionic v1

**Comment by khanghoang** [comment] 2018-05-08 22:48
@etakh @kdenz @akhilaet I want to update you guys that we're actively working on this. Some of the issues you reported are fixed, please help us verify them on your side.

**Comment by kdenz** [comment] 2018-05-09 03:04
@khanghoang Thank you very much for the attention!

There're still several issues on our side:

Our env:
- iOS 10/11
- React Native
- UI WebView

Express checkout button needs two or more clicks to open the checkout popup
http://youtu.be/Q-6U4165fpY?hd=1

At the login page, after choosing the "pay by card" option
The buttons at the bottom of the page, which is "Yes, I'd like to create a Paypal account", "I agree to ..." and "No, I don't want an account now" are extremely problematic:
1. Clicking on it will always make the screen scroll to top, which is highly annoying
2. Worst part - A lot of times it just doesn't work, no matter how many times I try to click on one of the buttons, it just doesn't have any effect, yet it'll still make the screen scroll to top.
http://youtu.be/WYMXpw7OImY?hd=1

I hope these issues can addressed, thank you!

**Comment by coderintherye** [comment] 2018-05-09 17:35
Just to note, we have also experienced the issue described by @kdenz with their second point. It's why I filed the other issue around the checkout demo having issues with iOS on iPhone so as to see if happening there as well (but the demo has separate issues)

**Comment by khanghoang** [comment] 2018-05-09 19:48
@kdenz @coderintherye thanks for your patience. I wanna let you guys know that AFAIK, we do not "officially" support React Native. But since the issues seem likely to happen on the web as well and I have a little bit experience with RN, I'd to give it a try.

@coderintherye can you help me to link your issue here so we can also keep track of it?

**Comment by coderintherye** [comment] 2018-05-09 20:47
@khanghoang https://github.com/paypal/paypal-checkout/issues/672 though really I'm just trying to solve for this issue, just wanted to be able to reproduce this issue on the demo site to make it easier for you'll to investigate

**Comment by kdenz** [comment] 2018-05-11 08:45
@khanghoang 
Hi, on WKWebView it's also problematic, as button clicks will lead to scrolling to top behaviors, thanks!
https://youtu.be/5mcLtIGlQLU

**Comment by kdenz** [comment] 2018-05-11 08:56
@khanghoang 
On Android 4.4 it's surprisingly fine
But some text displays are compressed together on smaller screen, making it difficult to read
![image](https://user-images.githubusercontent.com/12795428/39916107-3c1e818a-553c-11e8-80f8-4754fb0c7fc5.png)

**Comment by bluepnume** [comment] 2018-07-03 22:49
Closing this as it's our strong recommendation to launch the checkout in a full browser rather than a web-view.

**Closed by bluepnume** 2018-07-03 22:49 UTC
Labels: bug, need-feedbacks, p2
