### ISSUE TITLE
Dynamically loaded and destroyed PayPal button causes window close attempt on Edge/IE on navigation

### ISSUE THREAD

**Issue by evgrud** [paypal/paypal-checkout#357] opened 2017-05-26 12:22 UTC
This is the repro: [https://jsfiddle.net/argaz/62p9gu2d/](https://jsfiddle.net/argaz/62p9gu2d/)
In order to reproduce the issue using Microsoft Edge click the "Open modal" button, then close the modal by clicking the background. You should repeat this more than once. After that try to refresh the page and you'll get few "The site you're on is trying to close this window" prompts.

The calls seems to be coming from `drivers.js`. The line is:

> **this.window.close();**
> cleanUpWindow(this.window);
> delete this.window;

**Comment by bluepnume** [comment] 2017-05-28 19:42
Hey @evgrud thanks for reporting this! I've heard a few people complain about this, but as of yet I've been unable to repro. I'll try with your jsfiddle as soon as I can, but on vacation right now so may be a bit of a delay.

Can you also let me know your Edge version?

**Comment by evgrud** [comment] 2017-05-29 08:45
My current version, which was pretty recently updated is 15.15063, although it would behave similarly on older versions (I think that it happened on 14.14393 too).

**Comment by bluepnume** [comment] 2017-06-07 01:26
OK, thanks to your great example I was able to repro. Going to try to narrow down the cause now.

**Comment by bluepnume** [comment] 2017-06-07 05:24
Alright, this should be fixed. Please try clearing your cache and let me know if you still see the issue.

Turns out IE was interpreting "close this iframe" as "close the main parent window". I've added some safeguards to make sure that doesn't happen.

**Closed by bluepnume** 2017-06-07 05:24 UTC

**Comment by evgrud** [comment] 2017-06-07 08:54
Well done, got fixed!
