### ISSUE TITLE
bug: related_resources not populated on intent authorized

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#397] opened 2017-07-03 17:59 UTC
Need to update the mapping.  It works for sale

![image](https://user-images.githubusercontent.com/3578259/27803343-902b16a6-5fee-11e7-8828-8b0c3af02584.png)

Not authorize

![image](https://user-images.githubusercontent.com/3578259/27803512-744d6f64-5fef-11e7-8e04-a2d604468065.png)

Looks like authorize is not currently mapped in xo-buttonjs.

**Comment by trainerbill** [comment] 2017-07-03 18:01
@alnorth.  Here is your bug for updates.

**Comment by bluepnume** [comment] 2017-08-08 00:36
Dupe of https://github.com/paypal/paypal-checkout/issues/426 -- there's a fix in and it's ready to push.

**Closed by bluepnume** 2017-08-08 00:36 UTC
