### ISSUE TITLE
PP review page window - continue link not working 

### ISSUE THREAD

**Issue by ballawzi-pp** [paypal/paypal-checkout#514] opened 2017-10-26 14:41 UTC
### Description

On mobile web, when initiating the checkout processes on Safari and a user is redirected to the PayPal review page. If you switch tabs and go back to the website, the continue link doesn't take you to a PayPal review page, but you are able to close the window (the close `x` top right).

More details:

- reproducible **on mobile** using the [PayPal Checkout demo code](https://developer.paypal.com/demo/checkout/#/pattern/client), see steps below
- tested safari mobile (can not seem to find version) consistently
- cannot find the paypal.version on mobile but was able to replicate the bug on the interactive demo on the PayPal developer site. 

### Steps to reproduce

- go to the [PayPal Checkout demo code](https://developer.paypal.com/demo/checkout/#/pattern/client)
- click the PayPal Checkout button to initiate the payment process
- once the popup appears, go back to the website tab 
- try to use the 'Continue' button link to bring the popup back --> doesn't work 
(the close `x` works) 

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [x] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment] 2017-10-26 14:46
Thanks for the report! This is a duplicate of https://github.com/paypal/paypal-checkout/issues/503 so we can track it over there.

**Closed by bluepnume** 2017-10-26 14:46 UTC
