### ISSUE TITLE
Paypal Checkout : TypeError: styles is null

### ISSUE THREAD

**Issue by DavidMips** [paypal/paypal-checkout#822] opened 2018-08-24 07:39 UTC
Hi,

before today all was working well on sandbox account for paypal checkout. But today when testing, the console throw the error on attach file. But sometimes the error does not appear and the button work well until the last step of payment.
I'm using firefox for testing. On google chrome it's working fine.
I'm using the simple code of paypal checkout.

![2018-08-24_11h36_09](https://user-images.githubusercontent.com/42666576/44571478-e93d3800-a791-11e8-87a9-8ba6829f94b5.png)

![2018-08-24_11h33_02](https://user-images.githubusercontent.com/42666576/44571312-792eb200-a791-11e8-8958-3bc6180e2d8e.png)

Thank you for you help.

Kind regards.

David

**Comment by piotrkochan** [comment] 2018-08-24 12:10
Same here!

**Comment by gtzrvera** [comment] 2018-08-24 16:16
I have the same problem, in Chrome works fine, but in Firefox fails.
![captura de pantalla 2018-08-24 a la s 11 17 16](https://user-images.githubusercontent.com/3683101/44595595-2522ce00-a78f-11e8-997c-b2a02caabbaa.png)

**Comment by wchiquito** [comment] 2018-08-24 17:45
Does the problem remain?. I can't reproduce the problem in Chrome (sandbox | production) or Firefox (sandbox | production). paypal.version: "4.0.215".

**Comment by abarco** [comment] 2018-08-24 17:53
Hi all, the changes are being rolled back as we speak. This wasn't an issue with the incontext script, but due to a separate component. Apologies for the disruption. Please let me know if you do still see problems in your transactions due to this issue. If not, I'll be closing this issue by the end of day.

**Comment by abarco** [comment] 2018-08-24 17:54
@gtzrvera @DavidMips Can you guys let me know on what version of firefox were you able to reproduce this problem?

**Comment by gtzrvera** [comment] 2018-08-24 18:00
Effectively, the problems seems solved, @abarco the problem happened to me in Firefox 61.0.2 (64-bit) in Mac

**Comment by DavidMips** [comment] 2018-08-27 05:27
@abarco this was on Firefox 61.0.2 for me too.
The problem seems to be solved.
Thank you for your help.

**Closed** 2018-08-30 18:19 UTC
