### ISSUE TITLE
Client side payment execute is only available for REST based transactions

### ISSUE THREAD

**Issue by BenoitMercier** [paypal/paypal-checkout#711] opened 2018-06-09 16:17 UTC
I'm having a hard time with an intermittent error our users are getting:
"Client side payment execute is only available for REST based transactions"

We're using client-side REST only, and this works fine most of the time. But sometimes we have users who get the error.

I have not been able to reproduce it, but I managed to capture the error by sending it to the server for logging it.

**The err.stack is:**
Error: Client side payment execute is only available for REST based transactions
https://www.paypalobjects.com/web/res/e0d/1dbd5f2c8eff87d0ec061b32567a5/js/button.js?build=x:1269:36
memoizeWrapper@https://www.paypalobjects.com/web/res/e0d/1dbd5f2c8eff87d0ec061b32567a5/js/button.js?build=x:1623:38
value@https://www.paypalobjects.com/api/checkout.min.js:1:193377
https://www.paypalobjects.com/api/checkout.min.js:1:74384
value@https://www.paypalobjects.com/api/checkout.min.js:1:193377
https://www.paypalobjects.com/api/checkout.min.js:1:56823
O@https://www.paypalobjects.com/api/checkout.min.js:1:59461
T@https://www.paypalobjects.com/api/checkout.min.js:1:59820

paypal.version is 4.0.203

I had reports of this error for several browsers, at least Chrome and firefox. I had users try again later, and then it worked.

**Here's how the button is built:**
```
paypal.Button.render({
	env: ppCurrentEnv,
	client: {
		production: serverConfig.ppClientIdProduction, 
		sandbox: serverConfig.ppClientIdSandbox  
	},

	commit: true, // Show paypal button

	style: {
		label: 'buynow', // Label on the button
		fundingicons: true, // Shows credit card info
		branding: true, // false = no button
		size:  'medium', // small | medium | large | responsive
		shape: 'rect',   // pill | rect
		color: 'gold'   // gold | blue | silve | black
	},

	payment: function(data, actions) {
		return actions.payment.create({
			payment: {
				transactions: [ {
					amount: { total: option.price, currency: 'USD' },
					description: globalDescription,
					item_list: {
						items: [ {
							sku: option.part,
							description: option.description,
							quantity: 1,
							price: option.price,
							currency: 'USD',
						}]
					}
				}]
			},

			experience: {
				presentation: {
					brand_name: 'Universal Devices ' + (ppCurrentEnv=='production'?'Inc.':'[SANDBOX]')
				},
				input_fields: {
					no_shipping: 1
				}
			}
		});
	},

	onAuthorize: function(data, actions) {
		// Make a call to the REST api to execute the payment
		return actions.payment.execute().then(function() {
			// -----------------------------------------------------
			// From here we call a server API to process the purchase
			// But we don't get so far
			// -----------------------------------------------------
		});
	},

	onCancel: function(data, actions) {
		errorMessageDialog('Transaction is cancelled.');
	},

	onError: function(err) {
		errorMessageDialog('Paypal error');
		sendLog('pperror', 'Paypal API Error', err)
	}
}, paypalButtonTarget);
```

**Comment by abarco** [comment] 2018-06-11 18:06
Hi @BenoitMercier, thank you for your report. 

Since this is not an easily reproducible problem, is there any way you could forward a PAY ID of a transaction that exhibits this problem ( what is returned from the `actions.payment.create` call )? This can help us take a look at logs from our side and expedite triage of this issue.

**Comment by BenoitMercier** [comment] 2018-06-11 19:28
I'm currently not capturing nor logging the output of actions.payment.create. But I have the timestamp of the errors, and I can provide the previous and after payment IDs.

Here's 2 cases, with the previous and next successful transactions. The failing payment ID would be the one in between, for the same merchant ID as the successful ones.

Times are in UTC:
2018-06-11 03:30:36 Successful: PAY-2Y4488716Y9662308LMO6ZTA
2018-06-11 03:30:14 Error: Client side payment execute is only available for REST based transactions
2018-06-11 03:15:31 Successful PAY-73L14432GX5356709LMO6SCQ

2018-06-09 00:58:06 Successful: PAY-72S842205D995121CLMNSMEA
2018-06-09 00:57:47 Error: Client side payment execute is only available for REST based transactions
2018-06-09 00:38:37 Successful: PAY-89R10603XE685544VLMNSCKQ

In these 2 cases, I can see that the successful transaction following the failed transaction is for the same customer. In other words, the customer simply retried and it worked.

Let me know if you are able to find the failing transaction. If not, I'll add logging of the actions.payment.create output.

Thanks,

Benoit

**Comment by bluepnume** [comment] 2018-12-05 23:13
I believe this is fixed now. Please let me know if not.

**Closed by bluepnume** 2018-12-05 23:14 UTC
Labels: bug, p1
