### ISSUE TITLE
Edge 41 - Checkout popup fires onCancel immediately after loading

### ISSUE THREAD

**Issue by klk103** [paypal/paypal-checkout#750] opened 2018-07-16 16:07 UTC
### Description

We're using the Paypal button with checkout version 4.0.204 in an ASP.NET AJAX application. In Edge, when the button is clicked, the popup will open and begin rendering, then the overlay in the original window closes and leaves the popup open. Submitting the checkout form redirects to the root of our domain within the popup.

We're using checkout like so:

```js
paypal.Button.render({
	env: 'sandbox',
	style: {
		layout: 'vertical',
		size: 'medium',
		shape: 'rect',
		taglines: false
	},
	funding: {
		allowed: [paypal.FUNDING.CARD],
		disallowed: [paypal.FUNDING.CREDIT,paypal.FUNDING.ELV]
	},
	commit: true,
	payment: function () {
		return "existing payment ID from REST API";
	},
	onAuthorize: function (data, actions) {
		setTimeout(payPal_Authorized, 1, data);
		return actions.close();
	},
	onCancel: function (data) {
		console.log(data);
	}
}, '#paypal-button');
```
and the button appears in the HTML as
```html
<table class="style1 floatright" style="border-spacing:5px; border-collapse:separate">
<tr><th>Invoice Number</th>	<td>12345</td></tr>
<tr><th>Invoice Date</th>	<td>July 16, 2018</td></tr>
<tr>
	<td colspan="2">
		<div style="border:1px solid #000; border-radius:5px; padding:5px; text-align:center">
			<div>Amount Due</div>
			<div class="larger"><b class="larger">$1.00</b></div>
			<div id='paypal-button'></div>
		</div>
	</td>
</tr>
</table>
```
Logging at the _info_ level in the console shows:

```
ppxo_xc_ppcheckout_construct_parent [object Object]
ppxo_xc_ppcheckout_render_popup_to_win [object Object]
ppxo_xc_ppcheckout_delegate_popup [object Object]
ppxo_xc_ppcheckout_render_popup [object Object]
ppxo_xc_ppcheckout_call_prop_onRender [object Object]
ppxo_xc_ppcheckout_open_popup [object Object]
ppxo_xc_ppcheckout_resize [object Object]
ppxo_xc_ppcheckout_call_prop_payment [object Object]
[post-robot] iframe :: www.sandbox.paypal.com/webapps/hermes/button #send request :: xcomponent_delegate_ppcheckout :: * [object Object]
ppxo_xc_ppbutton_call_prop_onClick [object Object]
ppxo_button_click [object Object]
ppxo_xc_ppbutton_call_prop_payment [object Object]
[post-robot] fullpage :: **our payment page** #receive request :: xcomponent_delegate_ppcheckout :: https://www.sandbox.paypal.com [object Object]
[post-robot] fullpage :: **our payment page** #send response :: xcomponent_delegate_ppcheckout :: https://www.sandbox.paypal.com [object Object]
[post-robot] iframe :: www.sandbox.paypal.com/webapps/hermes/button #receive response :: xcomponent_delegate_ppcheckout :: **our domain** [object Object]
ppxo_xc_ppcheckout_load_url [object Object]
ppxo_xc_ppcheckout_call_prop_onDisplay [object Object]
```
There's a brief pause here, then the popup begins rendering
```
ppxo_xc_ppcheckout_detect_close_child [object Object]
ppxo_xc_ppcheckout_call_prop_onClose [object Object]
ppxo_close_trigger_cancel [object Object]
ppxo_xc_ppcheckout_call_prop_onCancel [object Object]
api_payment_id_ectoken_call [object Object]
api_response [object Object]
http_response_200 [object Object]
ui_api_payment_id_ectoken_success [object Object]
api_checkout_id_appData_call [object Object]
api_checkout_id_cart_call [object Object]
api_response [object Object]
http_response_200 [object Object]
ui_api_checkout_id_cart_success [object Object]
api_response [object Object]
http_response_200 [object Object]
ui_api_checkout_id_appData_success [object Object]
ppxo_xc_ppbutton_call_prop_onCancel [object Object]
ppxo_button_cancel [object Object]
```

This happens consistently in Edge on end user and development machines. This issue does **not** occur in the demos at https://developer.paypal.com/demo/checkout.

### Steps to reproduce

1. Click the PayPal button
2. The PayPal overlay appears
3. The checkout popup opens
4. The checkout popup HTML begins to load
5. The **onCancel** handler passed to **paypal.Button.render** is fired
6. The PayPal overlay in the original window disappears

All of this occurs without any user interaction beyond initially clicking the button. Clicking "Pay Now" in the popup (once the credit card form is filled in correctly) will redirect the popup to the **cancelUrl** address in the argument object passed to **onCancel**

I noticed that the **onCancel** event is fired because the periodic call to **isWindowClosed** returns true. I thought this was strange because the popup is still open, but Edge likes to do Edge things sometimes.

### Affected browsers

- [ ] Chrome
- [X] Edge 41.16299.547.0 (EdgeHTML 16.16299)
- [ ] IE

I'm assuming there's something about our site that's causing this; any help or insight you can provide would be much appreciated!

**Comment by klk103** [comment] 2018-07-17 16:05
[This](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15030423) sounds like a remarkably similar issue, and I was able to reproduce it successfully.

I set a trace on **win.closed** in **isWindowClosed** and clicked the button; it began returning _true_ as soon as the navigation from "about:blank" to "sandbox.paypal.com" occurred. Our development site and "*.paypal.com" are both Trusted Sites in our configuration, but I don't know whether "about:blank" is considered trusted.

**Comment by bluepnume** [comment] 2018-07-17 18:12
Sounds very much like issues we've faced with intranet/trusted mode. Can you please see if anything in this doc helps? https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md

**Comment by bluepnume** [comment] 2018-07-27 17:30
Closing this, will reopen if you're still facing the issue.

**Closed by bluepnume** 2018-07-27 17:30 UTC
Labels: question

**Comment by sandymca94** [comment] 2019-04-24 07:47
Hi, 

I am also getting the same issue - "Checkout popup fires onCancel immediately after loading" on Edge.

For temporary solution I did this as suggested in this article - "https://github.com/paypal/paypal-checkout-components/issues/959" but I can't give this solution to our client.

 I added the internal server and the "https://www.sandbox.paypal.com" size to the trusted Sites and restarted the Browser then its working fine.

Can some one please suggest me a proper solution for "Edge" browser.

Thanks
Sandeep

**Comment by sandymca94** [comment] 2019-05-02 05:04
@bluepnume the link - https://github.com/paypal/paypal-checkout/blob/master/docs/debugging/ie-intranet.md is no more available can you please check.

Because this issue on edge browser creating problem for us and i can't ask to client to add paypal site as trusted site.

Let us know for any other solution to fix edge browser issue to stop OnCancel event fire automatically.

**Comment by pokono** [comment] 2020-05-16 21:31
I still have this issue on every browser. Is there something I am missing?

**Comment by bluepnume** [comment] 2020-05-16 21:35
@pokono I'm struggling to reproduce this. Can you open a new issue and share the details? Thanks.
