### ISSUE TITLE
CORS error when using style.label === 'generic'

### ISSUE THREAD

**Issue by albv** [paypal/paypal-checkout#496] opened 2017-10-11 14:46 UTC
I am using PayPal Checkout together with braintree-web/paypal-checkout component. My code looks like this
```
braintree.paypalCheckout.create({
  client: clientInstance
}, function (createErr, paypalCheckoutInstance) {
  paypal.Button.render({
    env: 'sandbox', 
    locale: 'en_US',
    style: {
      label: 'generic'
    },
    payment: function () {
      return paypalCheckoutInstance.createPayment({
        flow: 'vault'
      });
    },

   ...
  }, '#paypal-button');
});
```
The button renders as expected but after clicking to it following error occurs 
```
Refused to display 'https://www.paypal.com/cgi-bin/webscr' in a frame 
because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```
With any other possible label value (```'checkout', 'pay', etc```) all works just fine.

**Comment by bluepnume** [comment] 2017-10-11 17:22
Thanks for the heads up. I've reverted the change, please clean your cache in 60 minutes and you should see this resolved. Closing as dupe of https://github.com/paypal/paypal-checkout/issues/495

**Closed by bluepnume** 2017-10-11 17:22 UTC
