### ISSUE TITLE
I did not receive mails for created and sended invoice in sandbox

### ISSUE THREAD

**Issue by KES777** [paypal/paypal-checkout#549] opened 2017-11-29 15:39 UTC
### Description

Hi. I create and send the invoice `INV2-24LR-96HG-VBBJ-SCZL`

I wanna to check visually created invoice, but did not receive it on my email.

Can you please help what I miss or did wrong?

I do this in my sandbox account

**Comment by bluelnkd** [comment] 2017-11-29 19:21
@KES777 I've reached out to our invoicing team for support on this item.

Regarding this Github project, it's focused primarily on just checkout.js integration method (https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/set-up-a-payment/).

If you've got any other specific details about steps to reproduce the issue you encountered again it'll be helpful to track down the root cause.

I'm also assuming you're not running into the same problem on paypal.com outside of the sandbox environment.

I'll be available to try to walk you through this further as we discuss with internal teams, but I'll be closing this issue specifically since it doesn't have relations to this project.

**Closed by bluelnkd** 2017-11-29 19:21 UTC

**Comment by bluelnkd** [comment] 2017-11-29 19:25
For our own internal tracking purposes the issue is being monitored under PPPLMER-42646 for further support.

**Comment by KES777** [comment] 2017-11-30 15:45
Hope this will be helpful:

```perl
sub invoice_create {
	my( $self ) =  @_;

	## VALIDATION
	my $payment =  $self->session->{ payment };
	## CREATE local and remote payment
	$payment->{ docn } =  $self->gen_docn;
	$payment =  PAYMENT->create( $payment );

	# Remote:
	my $merchant_info =  {
		email         =>  'feelsafe-facilitator@yandex.ru',
		first_name    =>  'First name',
		last_name     =>  'Last name',
		business_name =>  'FEEL SAFE INC.',
		phone =>  {
			country_code    =>  '004',
			national_number =>  '20245009375',
		},
		address =>  {
			line1        =>  '24.5 Old Northern Highway',
			city         =>  'Boston Village',
			state        =>  undef,
			postal_code  =>  '12345',
			country_code =>  'BZ',
		},
		website => 'https://feel-safe.net',
	};

	my $user =  $payment->User;
	my $billing_info =  [{
		email         =>  $user->email,
		first_name    => $user->firstname,
		last_name     => $user->lastname,
		business_name => $user->company,
		phone => {
			country_code => '38',
			national_number => $user->phone // '+380971234567'
		},
		address =>  {
			line1        =>  $user->address,
			city         =>  $user->city,
			country_code =>  $user->country_code,
			postal_code  =>  $user->zip,
			state        =>  $user->state,
		},
	}];

	my $items;
	for my $item ( $payment->Details->all ) {
		my $order =  $item->Invoice->Order;

		# Prepare description
		my $tariff  =  $order->Tariff->name;
		my $unit    =  $order->Tariff->period;
		my $account =  $order->options->{ last_package_id };
		my $desc =  "Tariff: $tariff ($account) | Unit: $unit";


		# Create payment item
		my $line = {
			name        =>  $desc,
			description => 'zzzzzzzz',
			quantity    =>  1,
			unit_price  =>  {
				currency =>  'USD',
				value    =>  sprintf '%.2f', $item->Invoice->suma,
			},
		};
		push @$items, $line;
	}

	# Create invoice
	my $invoice_id =  $self->paypal->invoice_create({
		number        =>  $payment->docn,
		invoice_date  =>  $payment->ctime,
		merchant_info =>  $merchant_info,
		billing_info  =>  $billing_info,
		items         =>  $items,
		note          =>  'Thank you',
		terms         =>  'No refunds after 30 days.',
	});

	# Send invoice to customer
	$invoice_id =  $invoice_id->json->{ id };
	$self->paypal->invoice_send( $invoice_id );

        $self->render( 'OK' );
}
```

Where `invoice_send` is:

```perl
sub invoice_send {
	my( $self, $invoice_id ) =  @_;

	my $res =  $self->request( post => $self->links->{ invoice } ."/${invoice_id}/send" );
}
```

What your MAIL system logs says for this invoice. 

**Was email sent to `kes-kes@yandex.ru` or not?**

**Comment by KES777** [comment] 2017-11-30 16:37
in `production` env for same request and data I get `VALIDATION ERROR`
```
{
  debug_id => 6ab467e2d58f7,
  details => [
    {
      location => merchantEmail,
      value => feelsafe-facilitator@yandex.ru,
    },
  ],
  information_link => https://developer.paypal.com/docs/api/invoicing/#errors,
  message => Invalid request - see details.,
  name => VALIDATION_ERROR,
}
```
