### ISSUE TITLE
payment() is called multiple times for the same checkout button click

### ISSUE THREAD

**Issue by sguryev** [paypal/paypal-checkout#161] opened 2017-01-22 15:45 UTC
Hi guys,

I'm using the sandbox environment. I have created the ExperienceProfile with ` "landing_page_type": "Billing"` in order to get the direct credit card payment feature (not sure if it's important actually.)

I'm using the Express Checkout adv. server integration flow
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/advanced-integration/

Here is the client side part:
![image](https://cloud.githubusercontent.com/assets/6978458/22181624/da61e024-e0a0-11e6-8906-159dba15b1cd.png)

For testing I'm using the sandbox **PERSONAL account with the $1 balance in order to check the insufficient funds flow.** 

First payment try works as expected: it suggests me to input the CC info or login. 
![image](https://cloud.githubusercontent.com/assets/6978458/22181651/59ed562a-e0a1-11e6-9ecf-311e6004bd84.png)

I'm choosing the login and then it suggests me to enter the CC info again (I think because of the insufficient funds)
![image](https://cloud.githubusercontent.com/assets/6978458/22181642/415d56e6-e0a1-11e6-8f86-4dfb323c0da6.png)

This is the end and I'm clicking the cancel link in the bottom of the **browser window**. It closes the **window** and calls the `onCancel` handler in the client-side.

Now I'm clicking the checkout button again and it opens the **modal** (since I'm already logged in) and call the `payment` handler with the ajax call to the server. 

After that in Console\Network I'm seeing the 400 response:
![image](https://cloud.githubusercontent.com/assets/6978458/22181693/32782a74-e0a2-11e6-82bb-0bbbe8b984dd.png)
With the content:
![image](https://cloud.githubusercontent.com/assets/6978458/22181708/70e7b612-e0a2-11e6-9e3b-b885a22ba103.png)

After that **modal popup** is turned out to the **browser window** and it calls the `payment` handler one more time. Which causes the second payment creation and in my server flow - new Order DB entity creation (also goods reservation, etc.)

**So the questions is: why does it call the payment handler one more time?**

Thank you!

**Comment by bluepnume** [comment] 2017-01-22 19:38
Hi @sguryev,

First off, thank you so much for the detailed issue report! This is probably the most thorough explanation of an issue we've had since opening this repo, I wish they were all like this!

Let me make sure I understand completely:

- You click the button and load up the popup window
- `payment()` gets called for the **1st** time
- You log in, then click cancel and return to the parent page
- You then click the button a second time, and load up the modal/lightbox iframe
- `payment()` gets called for the **2nd** time
- The modal prompts you to click "Log in with PayPal", and when you click a popup window is opened
- `payment()` gets called for the **3rd** time

Is that correct? If that's the case:

- The reason it's breaking you out into a popup window the second time is, due to our InfoSec policy we can't collect a new credit card from you, inside an iframe, so we need to break out into a popup window.
- If we're calling `payment()` a 3rd time, at that point, then that's a bug. Generally the rule should be "`payment()` will only be called once each time you click the checkout button on the merchant page"

So if that call is happening a 3rd time, I'll try to repro and figure out why, because you're right, that is an issue.

**Comment by bluepnume** [comment] 2017-01-22 19:46
Yeah, OK, I ran a quick test and I'm seeing that 3rd call. Really good catch! :) I'll figure out how soon we can make a fix for this.

**Comment by sguryev** [comment] 2017-01-22 19:47
Hi @bluepnume 

Thank you for you work. I understand that a lot of details means the fast solution)

Yes, you are correct. Except small adjustments.
On the step #6 I don't click the login (since I have clicked the Login button on the step #3 and I'm logged in currently - cookies, etc.)
So I'm seeing the iframe with the rotation indicator during it calls the `payment()` **2nd** time and then instead of showing the payment info it breaks out in to the browser window with the same rotation icon and calls the `payment()` 3rd time (without cancelling payment created on the 2nd time so I have one extra Order entity in the DB)

**Comment by sguryev** [comment] 2017-01-22 19:48
@bluepnume GREAT! Thank you! IF you need I can give you access to the staging server where you will be able to try it yourself. In case you want to test in in my configuration.

**Comment by sguryev** [comment] 2017-01-22 19:58
@bluepnume btw, maybe you can help me with the Negative Testing? Does it work with the REST API and express checkout flow? I have tried to enable the Negative Testing and pass the different codes as the `Transactions[0].Amount.Total` and `Transaction.ItemList.Items[0].Price` (because of the validation error that total amount doesn't match items price*quantity) but had no luck. It was the regular checkout process.

Sorry if it's a wrong place. I understand but I don't know where is the best place to ask. I have found several stackoverflow articles with mention that Negative Testing doesn't support the REST API. But they are pretty old so I hope that it's better now). So generally question is: **how I can tests different error situations (not related to the HTTP issues like 5** or 4**) with the REST API and Express Checkout?** I have created the PERSONAL accounts with $0 and $1 to test zero balance and insufficient funds (actually they work the same). But it's doesn't look enough.

Sorry for disturbing!
Thank you!

**Comment by bluepnume** [comment] 2017-01-22 20:32
Hi @sguryev 

On the 3rd `payment()` call issue, I've found the root cause. By default `payment()` is memoized every time the button is clicked, but slight variations in the params passed into the function were causing the memoization to not kick in.

I have a fix that I should be able to push out early next week.

----

On the negative testing front, I took a look but I don't see any reference to support for passing in error codes into the REST api. Actually, the error codes the REST api emits are totally different to the old nvp api.

I'm not sure what backend you're using, but would it be possible for you too mock out the paypal responses with the error codes you want to test? For example, if you're using node, we've had success using https://github.com/node-nock/nock in the past.

Thanks,
Daniel

**Comment by sguryev** [comment] 2017-01-22 20:37
Great thank you!
---------------------------
I'm using the ASP.NET MVC and WebAPI (using the official NuGet package). Generally I handle all the network related issues. 

But I also analyze the `payment.state` value during payment creation execution. And and I'm curious if it can be different to the I expected ones (with the 2xx http status code), how I can emulate it and what I should do in this case.

![image](https://cloud.githubusercontent.com/assets/6978458/22185713/a9619a04-e0fb-11e6-8c2f-784a0610a62e.png)

![image](https://cloud.githubusercontent.com/assets/6978458/22185714/adccbb14-e0fb-11e6-9506-ddb1299c56d6.png)

**Comment by bluepnume** [comment] 2017-01-23 21:28
Issue is fixed by this commit in xcomponent, will go out with the next release: https://github.com/krakenjs/xcomponent/commit/a526e4c718f123190616b6839bb5903d3b479229

---

For error cases, `payment.state` will not change, you'll get a 400 error with a `name` in the json of some error:

<img width="498" alt="screen shot 2017-01-23 at 1 26 01 pm" src="https://cloud.githubusercontent.com/assets/1219075/22223364/84e72c24-e16f-11e6-9aee-ab4b8def8044.png">
<img width="669" alt="screen shot 2017-01-23 at 1 26 14 pm" src="https://cloud.githubusercontent.com/assets/1219075/22223365/84e9b02a-e16f-11e6-9d9d-6a1ad1c61bc3.png">

More details: 

- https://developer.paypal.com/docs/api/errors/#error-responses
- https://developer.paypal.com/docs/api/payments/#errors

**Comment by sguryev** [comment] 2017-01-24 22:45
Thank you for the fix.
I'm using the following source: 
`<script src="https://www.paypalobjects.com/api/checkout.js"></script>`

When do you plan to release the next version? Will it be updated automatically?

------------------------

OK thank you. It looks like in case of any error I should get the **non 2xx status code.**.

**Comment by bluepnume** [comment] 2017-01-25 00:10
Yup, the fix should be in the next few days, and you'll automatically get it.

**Closed** 2017-02-03 19:30 UTC
Labels: bug, p2
