### ISSUE TITLE
"Powered by PayPal" causing blank space

### ISSUE THREAD

**Issue by PWaddict** [paypal/paypal-checkout#928] opened 2018-11-02 08:46 UTC
@bluepnume On "vertical" layout when the size is "responsive" the "Powered by PayPal" under credit cards icons is getting hidden but it's space still remains.

Here you can see the issue:
![paypal-credit-cards](https://user-images.githubusercontent.com/23142666/47902887-8f40a900-de8b-11e8-9d23-c4b3e5f8f2f9.jpg)

Here I disallowed the credit cards and there is no blank space:
![paypal](https://user-images.githubusercontent.com/23142666/47902905-99fb3e00-de8b-11e8-8855-b59d524722fb.jpg)

You can check the Vertical demo [https://developer.paypal.com/demo/checkout/#/pattern/vertical](https://developer.paypal.com/demo/checkout/#/pattern/vertical) too to see it live.

Please remove that blank space. Thanks.

**Comment by mcntsh** [comment] 2018-11-06 00:41
Duplicate of https://github.com/paypal/paypal-checkout/issues/830

**Closed by mcntsh** 2018-11-06 00:41 UTC
