### ISSUE TITLE
pre-template click issue before logging calls

### ISSUE THREAD

**Issue by rashid-aslam** [paypal/paypal-checkout#414] opened 2017-07-24 12:54 UTC
Although I have set data-log-level to "**error**" but still seeing logger calls in the console. And before the log calls are complete, clicking on the checkout button gives error of pre-template rendering click. Once the pre-template click error has appeared, any subsequent clicks doesn't initiate paypal payment. To avoid the pre-template erorr checkout button needs 3-4 seconds to be ready and it is creating a really bad user experience.

I am loading the checkout js script dynamically when a user selects payapal payment method on the checkout page.

**Comment by coderintherye** [comment] 2017-07-24 18:50
We are also experiencing this.
To reproduce, just:

1. load a page with the paypal checkout button (e.g. www.kiva.org/lend, checkout, then continue to payment, and on the payment page)
2. click the paypal checkout button immediately (hover over the spot where it will load and click as soon as you see it)
3. checkout with paypal button disappears 
4. After this, user is unable to checkout

This shows up in the log as the console message: logger.js:53 ppxo_button_pre_template_click

**Comment by bluepnume** [comment] 2017-07-25 15:05
Is this issue related to https://github.com/paypal/paypal-checkout/issues/416 ? Looks like the button is hidden regardless of whether it's clicked on.

**Comment by bluepnume** [comment] 2017-07-25 18:28
Other issue was resolved so closing this, unless you have any more info. Thanks!

**Comment by rashid-aslam** [comment] 2017-07-25 18:58
Hi,  this was not related to #416. It is clearly different issue.  Do you need any clarification?

**Comment by bluepnume** [comment] 2017-07-25 19:00
Yes, please -- can you reproduce this anywhere else, like for example on https://developer.paypal.com/demo/checkout/#/pattern/client ?

How do you figure the issue is unrelated, if the button on kiva.org was disappearing as a result of a code change on their side?

**Comment by coderintherye** [comment] 2017-07-25 19:27
@bluepnume I think you may be confounding the two issues. I was tagging on to Rashid's report as we saw a similar symptom. I'll delete my comment to avoid confusion.

**Comment by rashid-aslam** [comment] 2017-07-26 04:24
@bluepnume Please see the screenshot. I got two events where the popup didn't open. So there is at least one event where the popup doesn't appear and user has to click again to open it.

![paypal checkout integration patterns - google chrome_001](https://user-images.githubusercontent.com/6771187/28604415-fb3c2776-71e3-11e7-9dda-fbfd7c6b98d1.png)

**Comment by bluepnume** [comment] 2017-08-09 20:57
Can you please let me know if you still see this issue? This should be resolved by now.

**Closed by bluepnume** 2017-08-09 20:57 UTC
Labels: bug, p1

**Comment by rashid-aslam** [comment] 2017-08-10 05:20
@bluepnume Yes I still see the issue

**Comment by bluepnume** [comment] 2017-08-10 07:33
Specifically this comment:

> any subsequent clicks doesn't initiate paypal payment

Can you confirm that the button is totally unusable if you click before it's ready? I've been unable to repro that.

**Comment by rashid-aslam** [comment] 2017-08-10 08:16
> any subsequent clicks doesn't initiate paypal payment
this is fixed. after it loads the button works fine.

Only thing remaining is the pre-template-click. This you can still see on the demo page

**Comment by bluepnume** [comment] 2017-08-10 16:44
OK, thanks. This is a known issue, we're working on making the pre-rendered button clickable.

**Comment by MaxDBN** [comment] 2017-09-19 13:40
@bluepnume I'm also having this issue now. Is there any temporary solution?

**Comment by andreaslillebo** [comment] 2017-11-10 02:12
This appears to still be an issue.

It can be reproduced by going to this page and clicking on the PayPal button within a few seconds after it loads:
https://developer.paypal.com/demo/checkout/#/pattern/client

<img width="1352" alt="paypal_button_issue" src="https://user-images.githubusercontent.com/24457101/32639412-2e8b16c4-c607-11e7-98af-3d5c4c91231c.png">

Sometimes it may take up to 10 seconds before the button reacts. If a user clicks on the button before it is fully loaded, the button appears dead and there is no feedback to the user.

**Possible solutions:**

1. Show a loading/spinner icon on the button before it is ready to be clicked. 
2. Have the "pre_template_click" trigger a loading/spinner icon on the button, then show the popup when it is ready. This would let the user know that the button has been clicked, and that something is happening.

Solution number 2 would probably be the best user experience.

**Comment by axul** [comment] 2017-12-14 15:45
Still having this issue, and I cant find a way to catch the ppxo_button_pre_template_click event if there is one

**Comment by bluepnume** [comment] 2017-12-14 22:34
@axul -- which environment -- sandbox or production?

**Comment by axul** [comment] 2017-12-18 14:41
@bluepnume both cases

**Comment by axul** [comment] 2017-12-18 14:42
@bluepnume  ![captura de pantalla 2017-12-18 a la s 9 41 21 a m](https://user-images.githubusercontent.com/5530073/34111431-b30327f0-e3d7-11e7-9545-29fdc4cb8fb8.png)

**Comment by raRaRa** [comment] 2018-09-23 10:05
I also have the same issue. Is there any event that is dispatched when the button is ready?
