### ISSUE TITLE
Xoon flow executing onCancel, not onAuthorize

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout#767] opened 2018-07-30 13:58 UTC
### Description

Please provide a short description of the issue here, along with:

![image](https://user-images.githubusercontent.com/3578259/43401767-a2fb78c6-93d6-11e8-83a6-76bb727d00c2.png)

https://www.sandbox.paypal.com/webapps/xoonboarding?locale.x=en_US&fundingSource=paypal&sessionID=e06a9e331c_geztunbuhi2tq&buttonSessionID=c9bd4d8763_geztunbxhiztc&env=sandbox&logLevel=warn&uid=64e9b0d0c3&version=4&token=EC-1K731007A3199125A&xcomponent=1&country.x=US&locale.x=en_US&country.x=US&locale.x=en_US#/checkout/guest

### Steps to reproduce

Go to demo app and add onCancel callback.  Pay with guest and do not create account.  Spinner takes a while and then executes onCancel.

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by jkomusin** [comment] 2018-10-03 20:32
Running into this same issue, able to reproduce through the React component integration, from Firefox 62.0.2

**Comment by mcntsh** [comment] 2018-11-07 19:17
@trainerbill Is this still happening? I just tried to repro on sandbox from the demo app by doing a guest checkout and I never hit the `onCancel` callback.

**Comment by trainerbill** [comment] 2018-11-07 20:33
@mcntsh the issue in the past was that any errors in Xoon would call the onCancel callback.  So you have to actually force an error in Xoon.  The easiest way to do this is to use the 4111-1111-1111-1111 card number.  It looks like now they added a little error screen that says try again or return to merchant.  However when you click return to merchant it does go to onCancel, which may be appropriate since it is a "cancel" at that point.  Previously the popup would just close and onCancel would fire.

So I am not sure if it is an issue anymore or not.  If Xoon was fixed to always show that error page I think we are good to go.

**Comment by mcntsh** [comment] 2018-11-08 20:56
OK understood. It looks like the guest flow does indeed forward error paths during onboard to `/checkout/genericError` and the `onCancel` callback is only being called after the return-to-merchant link is clicked. I'm not seeing any other references to this callback in Xoon to `onCancel`, so I'll close this out. If the issue pops up again we can reevaluate 👍

**Closed by mcntsh** 2018-11-08 20:56 UTC
Labels: bug
