### ISSUE TITLE
iOS Chrome Issue

### ISSUE THREAD

**Issue by yabdab** [paypal/paypal-checkout#489] opened 2017-10-05 14:29 UTC
I have noticed that on iOS Chrome ( phone, not ipad  ) after Pay Now is clicked, a default Google Search page is loaded. The parent checkout page is still in play, but the popover page does not get deleted so the customer can see the final page of the check out ( post - paypal ).

Is this expected behaviour?

**Comment by bluepnume** [comment] 2017-10-05 17:14
Hmm, no, that's definitely not expected. The parent window should close the child window.

Can you clarify -- does it still switch back to the parent page, with the child open in the background, or does the child stay focused?

**Comment by yabdab** [comment] 2017-10-05 17:40
It stays focused on the "Google Search" page. I had to go through the open tabs to get back to the parent page. The parent page DID receive the callback and acted upon it though.

**Comment by bluepnume** [comment] 2017-10-05 19:06
Weird. I wonder if there's some bug in the win.close() -- let me try to repro and I'll let you know. Thanks for letting me know

**Comment by bluepnume** [comment] 2017-10-09 23:37
@khanghoang -- can you take a look at this one? A few hints:

Close is called here:

https://github.com/paypal/paypal-checkout/blob/master/src/components/checkout/component.js#L316

Which calls:

https://github.com/krakenjs/xcomponent/blob/master/src/component/parent/index.js#L942

Which eventually calls:

https://github.com/krakenjs/xcomponent/blob/master/src/component/parent/drivers.js#L263

So, first step would be to make sure `window.close()` is actually being called. Second step would be to figure out if chrome is respecting the`close()` call.

**Comment by khanghoang** [comment] 2017-10-10 00:10
@yabdab I can't reproduce it on my iPhone. Can you give us more information?

- iOS device: (e.g iPhone 6 Plus)
- Your iOS version: (e.g iOS 11.0.1)
- Is your Chrome App latest version? (check **updates** tab in AppStore)
- Does it happen on [https://developer.paypal.com/demo/checkout/#/pattern/client](https://developer.paypal.com/demo/checkout/#)?
- Screenshots or video are appreciated.

**Comment by bluepnume** [comment] 2017-10-10 00:13
On that note -- for any new issues like this, please be sure to follow the github template:

```
### Description

Please provide a short description of the issue here, along with:

- Screenshots or videos that show the issue
- Your code
- The `paypal.version` from your browser console
- The exact browser version
- A link to your page with the issue, if possible
- All console logs during the time of the issue, especially error messages
- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
- Does the issue occur consistently, or intermittently?

### Steps to reproduce

Please provide each individual step required to reproduce the issue

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other
```

(@khanghoang -- if you see anything missing here feel free to add it 👍 )

**Comment by khanghoang** [comment] 2017-10-30 20:50
@yabdab we close this issue since we can't reproduce it. Feel free to reopen it you want.

**Closed by khanghoang** 2017-10-30 20:50 UTC
Labels: bug, p1
