### ISSUE TITLE
Closing the incontext window quickly throws error when canceling

### ISSUE THREAD

**Issue by PhilibertDugas** [paypal/paypal-checkout#601] opened 2018-02-13 15:31 UTC
### Description

Please provide a short description of the issue here, along with:
When opening the Paypal in-context window & closing it quickly followed by canceling, an error is thrown and the button becomes unresponsive

- Screenshots or videos that show the issue
![paypal-error](https://user-images.githubusercontent.com/5460957/36157824-b51820a6-10a8-11e8-81ae-25e75f701df5.gif)

- Your code
Using the demo from https://developer.paypal.com/demo/checkout

- The `paypal.version` from your browser console
```
window.paypal.version
"4.0.173"
```

- The exact browser version
Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- A link to your page with the issue, if possible N/A

- All console logs during the time of the issue, especially error messages
![image](https://user-images.githubusercontent.com/5460957/36157925-fda2c326-10a8-11e8-8ba3-934d3e78c6ed.png)

- Does the issue also occur at [developer.paypal.com/demo/checkout](https://developer.paypal.com/demo/checkout)?
Yes

- Does the issue occur consistently, or intermittently?
Consistently

### Steps to reproduce
* Click on the paypal button that opens the incontext window
* close the incontext window before it finishes loading
* click on the cancel link overlaying the page

### Affected browsers
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [ ] Web View / Safari ViewController
- [ ] Other

**Comment by bluepnume** [comment] 2018-03-02 20:01
Thanks for the report, I'll take a look!

**Comment by mcntsh** [comment] 2018-11-07 19:18
Duplicate of https://github.com/paypal/paypal-checkout/issues/845

**Closed by mcntsh** 2018-11-07 19:18 UTC
Labels: bug, p2
