### ISSUE TITLE
iOS Firefox crashes when tapping login button

### ISSUE THREAD

**Issue by crookedneighbor** [paypal/paypal-checkout#417] opened 2017-07-25 20:50 UTC
### Description

iOS Firefox crashes after tapping login button

### Steps to reproduce

Open iOS Firefox and try to log in. When you press the login button, the app crashes.

### Affected browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE
- [ ] Chrome Mobile/Tablet
- [ ] Safari Mobile/Tablet
- [x] Web View / Safari ViewController (iOS Firefox)
- [ ] Other

**Comment by vishakha94** [comment] 2017-07-25 21:23
Hi @crookedneighbor,
I wasn't able to re-produce the issue mentioned. Would you be able to provide a little more detail on which button you are actually pressing?
Nothing crashes for me when I try to click on login button after being re-directed from the checkout button on iOS Firefox.

**Comment by crookedneighbor** [comment] 2017-07-25 21:27
The login button. 

In sandbox, when I try to login, pressing the login button after filling in the email and password causes it to crash. Not sure if the same is happening in prod or not.

![image uploaded from ios](https://user-images.githubusercontent.com/2916945/28594563-091ea776-7156-11e7-80f9-402eb3fd682e.jpg)

**Comment by crookedneighbor** [comment] 2017-07-25 21:28
iPhone 6
iOS 10.3.2
Firefox 8.0.1 (4659)

**Comment by bluepnume** [comment] 2017-08-08 01:15
Closing as dupe of https://github.com/paypal/paypal-checkout/issues/405

**Closed by bluepnume** 2017-08-08 01:15 UTC
Labels: bug, p1
